### ISSUE TITLE
🐛 [BUG] -   Unable to import module 'lambda_handler': No module named 'openai'

### ISSUE THREAD

**Issue by marcelfolaron** [FullStackWithLawrence/aws-openai#191]
### Description

Hi,
I was following the instructions for the REST API and for the most part everything worked great but the vast majority of endpoints on postman return the following error message:

    "errorMessage": "Unable to import module 'lambda_handler': No module named 'openai'",
    "errorType": "Runtime.ImportModuleError",

I tried verifying that I am using python 3.11 and that everything gets installed correctly but can't really figure out what the issue is.

Thank you

### Reproduction URL

https://github.com/FullStackWithLawrence/aws-openai

### Reproduction steps

```bash
1. Follow instructions on https://github.com/FullStackWithLawrence/aws-openai/tree/main/api
2. Try running passthrough.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Mac

**Comment by lpm0073** [comment]
Hi @marcelfolaron [this](https://github.com/FullStackWithLawrence/aws-openai/blob/main/api/terraform/python/lambda_openai_v2/lambda_handler.py#L34) is the exact line of code to which the import error is referring. This is a symptom indicating that your Lambda Layer is either not present or is corrupted (i'm guessing the former). More specifically, the package 'openai' is included in the contents of the AWS Lambda Layer that Terraform creates, [here](https://github.com/FullStackWithLawrence/aws-openai/blob/main/api/terraform/lambda_layer.tf).

Creation of the Lambda Layer is by far the most technically complex operation that Terraform performs during this build. Of note:

**you need Docker and Docker Compose, which are used in order avoid strange platform incompatibility issues that can surface with some of the larger PyPi packages that are included in the build such as NumPy and SciPy. You can refer [here](https://github.com/FullStackWithLawrence/aws-openai/blob/main/api/terraform/python/layer_genai/create_container.sh) and [here](https://github.com/FullStackWithLawrence/aws-openai/blob/main/api/terraform/python/layer_genai/Dockerfile) to see how Docker Compose is being used to create the Layer.**

**Comment by marcelfolaron** [comment]
Thank you for your response! 
But yeah this is rather puzzling to me. The screenshots align and yet I am still getting this error. I'll take another look at the docker set up. I read somewhere else that this could be a version alignment issue. Which openAI python package versions are supported? 

<img width="1511" alt="image" src="https://github.com/FullStackWithLawrence/aws-openai/assets/47038998/275bf00e-1957-4e1f-966b-050dc0241a4d"> 
<img width="1511" alt="image" src="https://github.com/FullStackWithLawrence/aws-openai/assets/47038998/c44773b2-8d07-4658-bc6d-51cf3aedf1fb">

**Comment by marcelfolaron** [comment]
Maybe related: Have you seen any issues running everything on a Macbook M1. I did have to go through some additional steps getting terraform running on my mac due to Arm incompatibility.  In particular I had to compile the template 2.2.0 module using https://kreuzwerker.de/en/post/use-m1-terraform-provider-helper-to-compile-terraform-providers-for-mac-m1

**Comment by lpm0073** [comment]
Yes. the terraform run-time issues are resolved at this point, so nothing to discuss on that front. but the platform-specific issues i mention above regarding the build for the Layer is something specific to Python that is permanent. at issue is that certain, large PyPi packages include Cython as well as really old source files such as C and C header files which have to be compiled for the platform on which they'll run (ie Amazon Linux). Hence, the Dockerfile

**Comment by marcelfolaron** [comment]
Thank you for your help! I think I am almost there. Was able to fix my python configuration so that the openAI import works. I am now running into a problem with pydantic_core. It appears to be a platform issue as well since it's pulling the arm version on my mac when I need the x86 version. Is that part of the docker build as well?

**Comment by lpm0073** [comment]
That sounds familiar. you might want to review this thread -- https://github.com/pydantic/pydantic/discussions/4699.
More generally, the terraform variable compatible_architecture should be set to "x86_64" (see https://github.com/FullStackWithLawrence/aws-openai/blob/main/ap
i/terraform/variables.tf#L133), and you can confirm from this window in the AWS console

<img width="1198" alt="Screenshot 2023-12-14 at 6 28 25 a m" src="https://github.com/FullStackWithLawrence/aws-openai/assets/1178819/a31ad31d-1563-4a26-95dc-d5e14c8b4994">

**Comment by lpm0073** [comment]
[see here](https://github.com/FullStackWithLawrence/aws-openai/blob/main/api/terraform/python/layer_genai/Dockerfile#L6)

**Comment by lpm0073** [comment]
Closing this, as there hasn't been any further discussion in the last month.
